# Generated by Django 5.2.6 on 2025-10-09 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='courses',
            new_name='course',
        ),
        migrations.AlterField(
            model_name='students',
            name='email',
            field=models.EmailField(max_length=50),
        ),
    ]
